name: Build and Notify - POC Updated

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]

jobs:

  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on pipeline start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "The build has been triggered."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  build:
    runs-on: ubuntu-latest
    needs: notify-start  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: BuildPrint
        run: echo "build started"

      # - name: sleep
      #   run: sleep 120

      - name: Send notification on pipeline start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "The build has been completed successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


  notify-duration:
    runs-on: ubuntu-latest
    needs: notify-start
    steps:
      - name: Check duration and send notification if more than 5 minutes
        run: |
          start_time=$(date -u '+%s')
          end_time=$(date -u '+%s')
          duration=$((end_time - start_time))

          while [ $duration -le 35 ]; do
            sleep 30  # Adjust the sleep interval as needed
            end_time=$(date -u '+%s')
            duration=$((end_time - start_time))
          done

          echo "::set-output name=send_notification::true"
        id: check_duration

      - name: Send notification on long-running pipeline
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "The build has been running for more than 5 minutes."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: steps.check_duration.outputs.send_notification == 'true'
