name: Build and Notify - Final Updated

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]

jobs:

  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on pipeline start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "The build has been triggered."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    
  notify-duration:
   runs-on: ubuntu-latest
   needs: notify-start
   steps:
     - name: Check duration and send notification if more than 5 minutes
       run: |
         start_time=$(date -u '+%s')
         end_time=$(date -u '+%s')
  
         echo "build started"
         sleep 120
  
         end_time=$(date -u '+%s')
         duration=$((end_time - start_time))
  
         if [ $duration -gt 30 ]; then
           echo "::set-output name=send_notification::true"
         fi
         if [ $duration -lt 30 ]; then
           echo "::set-output name=send_notification::false"
         fi
       id: check_duration
  
     - name: Send notification on long-running pipeline
       uses: slackapi/slack-github-action@v1.24.0
       with:
         payload: |
           {
             "text": "The build has been running for more than 5 minutes."
           }
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
       if: steps.check_duration.outputs.send_notification == 'true'

     - name: Send notification on long-running pipeline
       uses: slackapi/slack-github-action@v1.24.0
       with:
         payload: |
           {
             "text": "The build has been completed withing the timeframe"
           }
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
       if: steps.check_duration.outputs.send_notification == 'false'