name: Build and Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo "hi"
    #   - name: Notify Slack
    #     uses: actions/notify-slack@v3
    #     with:
    #       slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    #       status: ${{ job.status }}
    #       channel: '#your-slack-channel'
    #       icon_url: 'https://github.com/favicon.ico'
    #       message: |
    #         Workflow: ${{ github.workflow }}
    #         Branch: ${{ github.ref }}
    #         Job: ${{ job.name }}
    #         Status: ${{ job.status }}
  
      - name: slack-send
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel ID where message will be posted. Needed if using bot token
          channel-id: test-poc
          # Message to post into Slack. Needed if using bot token
          slack-message: slack message
          # JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead
          payload: # optional
          # path to JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead. If payload is provided, it will take preference over this field
          payload-file-path: # optional
          # The timestamp of a previous message posted. It will update the existing message instead of posting a new message
          update-ts: # optional
              