name: Build and Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo "hi"
    #   - name: Notify Slack
    #     uses: actions/notify-slack@v3
    #     with:
    #       slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    #       status: ${{ job.status }}
    #       channel: '#your-slack-channel'
    #       icon_url: 'https://github.com/favicon.ico'
    #       message: |
    #         Workflow: ${{ github.workflow }}
    #         Branch: ${{ github.ref }}
    #         Job: ${{ job.name }}
    #         Status: ${{ job.status }}
  
      - name: Publish to slack channel via bot token
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'SLACK_CHANNEL_ID' # ID of Slack Channel you want to post to
          slack-message: 'posting from a github action!' # The message you want to post
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
              